const P1 = `In 1966 officials of La Carlota, then a fledging City, also believed in the power of education to uplift the lives of the youths and bring progress in the community. By authority of Republic Act No.4585 also known as the "The Charter of the City of La Carlota," city officials led by Mayor Jaime F. Marino and Vice Mayor Prospero C. Rojo, City Councilors Loreto V. Valera, Manuel C. de los Reyes, Jose A. Liansing, Anacleto C. Jereza Jr., Jose Y. Jalandoni, Jose R. Ferrer, Renato L. Sofio and Emilio M. Zaldivar laid the foundations for the creation of La Carlota City College. Mr. Jose Varon, then Superintendent of the La Carlota City Division was appointed Director of the City College. Classes opened in 1967. At that time, La Carlota High School shared its facilities with the City College. Classes were almost always held in the evenings.`
const P2 = `In 1969, the City Council enacted Ordinance No. 37 also known as the "Charter of the La Carlota City College," drafted by Director Varon, Councilor Valera and College Registrar Roberto Liberiaga. Signing the College Charter were City Mayor Luis G. Jalandoni, Jr., Vice Mayor Jose A. Liansing and City Councilors Loreto Valera, Marcelo Aguirre, Sr., Hernani J. Jimenez, Sr., Vicente T. Flores, Sr., Manuel A. Verba, Sr. Serafin P. Alova, Sr., Rafael E. Marino, and Rodolfo M. Uriarte.`
const P3 = `In accordance with the Charter, the Board of Trustees which shall direct and manage the affairs of the College shall be composed of the City Mayor, Chairman of the Committee on Education of the Municipal Board, City Superintendent of Schools, President of the Federation of Parents-Teachers association of La Carlota and President of the Alumni Association of the College. The first Board of Trustees was then composed of City Mayor Luis G. Jalandoni, Jr. as Chairman, Councilor Valera as representative of the City Council, Mr. Varon in his new capacity as City Superintendent of Schools, and Mr. Antonio Aplaon, as representative of the Federation of Parents-Teachers Association in La Carlota City.`
const P4 = `In the following year, Mr. Varon relinquished his position as College Director to dedicate himself to being Superintendent of Schools. This led to the appointment by the Board of Trustees of Atty. Marcelo C. Jalando-on as the first College President. He resigned in 1975 and was succeeded by Dean Elisa D. Regner. Mrs. Regner, who wrote the lyrics to the Alma Mater song, did not stay long as President. She retired from the service in 1976, leaving the position vacant for a while until Dean Amelia I. Valera was appointed College President in June, 1977.`
const P5 = `Dr. Amelia Valera served for the longest time as College President from 1977 up to her retirement in 2005. By then college enrollment was steadily growing from 234 in 1967 to approximately 2,500 in 2005. Increased enrollment created a need for additional facilities. During the first semesters of S.Y. 2016-2017 the college already hosted almost 6,000 enrolees.`
const P6 = `In November 1988 the Board of Trustees of La Carlota City, La Castellana and Pontevedra Planters Foundation, Inc. donated to the city government the site and buildings of the Planters Foundation Technical School in Brgy Cubay. Providentially, City Mayor Juancho Aguirre turned over the facility to La Carlota City College, thereby answering the college's need. Today, the Cubay campus is still sometimes called "Planters" as a throwback to its roots. It used to house the Midwifery department and presently, the Business and Management (Commerce), Criminal Justice Education (Criminology), and Agriculture departments.`
const P7 = `In 1984, the College opened its Graduate School Department which offered Master of Arts in Education until 1987. Through a consortium with Aklan State College of Agriculture, the College was able to offer Master of Science in Agriculture, Master in Public Administration (MPA) and Master of Arts major in Educational Management. In 1996, the Commission in Higher Education gave the authority in CHED Order No. 36, for La Carlota City College to offer its own programs.`
const P8 = `In January 2001, the College submitted itself for accreditation and the Accrediting Agency of Chartered Colleges and Universities (AACCUP) awarded the Bachelor in Elementary Education (BEEd) Program with level 1 status, and level 2 in December 2002. Bachelor in Business Administration, Bachelor of Arts and Bachelor of Science in Agriculture were granted level 1 status in 2003.`
const P9 = `The college was able to expand its facilities through individuals, civic groups, government officials, and efforts of the faculty and staff. Construction of the Jose P. Rizal Center (JPRC Bldg.) was courtesy of Congressman Edward Matti computers, printers, type writes, band instruments, and books for the College Library. Governor Joseph Marañon donated funds for the construction of Friendship Hall, two restrooms and installation of 10 lamps along the JPRC driveway.`
const P10 = `Two women's civic groups in La Carlota also left their touch on campus. From the Kababaihang Rizalista came monuments of Dr. Jose P. Rizal and Andres Bonifacio. They also solicited from the congressional party-list group Abanse Pinay! A donation of a one-room building which was called Filipinas building. It is now used as a computer laboratory with computers being supplied by then Mayor and Chairman of the Board, Hon. Jeffrey P. Ferrer. Meanwhile the Green Arcade Rose in the main campus through the efforts of the La Carlota City Ladies Green Circle, Inc. The women's groups also held frequent symposia on campus on issues of national concern.`
const P11 = `During the first mayoral term of Hon. Luis J. Jalandoni III from 2001 - 2004, he was responsible for the widening of the JPRC lobby and cementing of the horseshoe-shaped JPRC driveway. The newly erected Rose of Sharon Hall which was donated by a philanthropic couple from La Carlota who migrated to America, Engr. Rodulfo Niere and wife Violeta. The Nieres also earlier donated the Haven of Hope Center while also giving scholarships to many LCCC students.`
const P12 = `The Faculty also pitched in their efforts to improve the campus. From their donations they built Ugyunan Arcade, "Ugyanan" being an Ilonggo word for "cooperation" or "joint effort".`
const P13 = `Build a Better City College, a fund-raising effort during Dr. Valera's term, made the construction of the third floor, Founders' Building and Founders' stage possible. Dr. Amelia Valera retired in May 2005, after which the Board of Trustees then headed by City Mayor and Chairman Jeffrey P. Ferrer appointed Dean Lydia V. Peñafiel as Officer-in-Charge. She assumed the presidency on July 1, 2007.`
const P14 = `Through the efforts of mayors Hon. Luis J. Jalandoni III and Hon. Jeffrey P. Ferrer, a two-classroom building was built in Cubay campus donated by the Chinese Chamber of Commerce. Presently, it is used by Agriculture students in the conduct of some of their classes. President Peñafiel maintained the quality of Education during her term. She also facilitated the completion of the graduate school building. In the later part of the year, she retired from the service due to mandatory retirement age.`
const P15 = `Dr. Bullos' term started upon the retirement of President Lydia Peñafiel in 2007. The Board of Trustees under the chairmanship of Mayor Demie John C. Honrado appointed Administrative Officer Fatima G. Bullos first to be officer-in-charge and later as College president. She was responsible for initiating the Adopt-a-Classroom project by which the college was able to acquire chairs, steel tables, projectors and other equipment. Through her efforts and with the support of Hon. Jeffrey P. Ferrer came the launching of "Let's Go Scholarship Program" which gave numerous graduate school scholarships at the 4th District enabling many professionals to improve their personal efficiency and work performance. She likewise expedited the "Cyber Enhancement Program" which made the students of LCCC knowledgeable of computers and Internet. The 40 computer units were donated by Hon. Jeffrey P. Ferrer.`
const P16 = `Growing up in abject poverty, Dr. Bullos distinguished herself academically from elementary until her college years. Dr. Bullos graduated from B.S. Commerce, cum laude at La Carlota City College and was employed by her alma mater after graduation. She rose through the ranks from the position of clerk to that of College president. Having finished her Masters in Public Administration at LCCC graduate school, summa cum laude, Dr. Bullos takes pride in being a product of the La Carlota City College in a model of success.`
const P17 = `Through times of transition, the school administration, as well as Dr. Fatima G. Bullos reticulated organizational involvement, her serving as Board Director of Association of Local Colleges and Universities (ALCU) and Association of Local Colleges and Universities Commission on Accreditation (ALCUCOA), and treasurer of Association of Colleges and Universities of Negros Occidental (ACUNO). The representation in these organizations contributed to college's academic health and development. Through these linkages, La Carlota City College is at its forefront in discussion of issues concerning tertiary education.`
const P18 = `After Mayor Jeffrey Ferrer's term came that of Hon. Demie John Canlas Honrado. He continued the scholarship program at La Carlota City College, thereby enabling many needy students to get their college degree and fulfill their dreams. Mayor Demie also facilitated the repair of the extension rooms at Rodriguez Building in Cubay campus.`
const P19 = `Perhaps a neophyte to politics in public governance during her first term as mayor of La Carlota in 2010, Hon. Mayor Atty. Juliet Marie Ferrer effected many programs that greatly benefited the City College. Her strengthening of the criteria for the government scholarship led to the financial stabilization of the college. With her financial award for excellence, she enabled the construction of the three-classroom building in Cubay Campus, the repair and renovation of Rodriguez Building, Cubay Campus and the conversion of the former Machine Shop at Cubay Campus into eight additional classrooms. This infrastructure work helped to answer the further need for more rooms to accommodate the ever growing enrolment.`
const P20 = `During her last year as Mayor, Atty. Ferrer facilitated the painting of the Founders' building, main campus and Rodriguez building in Cubay. The library, laboratories, Home Arts Building and Administration building in Cubay campus were repaired and renovated in 2016. An improved Deftac area was created for the Criminology department, and 5 high powered microscopes and projectors were acquired to enhance the instruction.`
const P21 = `The college is proud of its graduates' performance in the board examinations where two midwifery graduates even distinguished themselves by landing as topnotchers in the board examinations. In 2014, Glaiza M. Atilano placed third in the National Midwifery Board. In the following year, fellow midwifery graduate Winielyn A. Espenorio duplicated the achievement, placing 7th in the board exams. In the recent October 2016 Criminologist Licensure Examination, Shenai Juance placed 5th in the list out of 34,768 examinees. In other courses with board examination such as Teacher Education, Midwifery and Agriculture, LCCC graduates have garnered scores which are higher than the national passing average.`
const P22 = `Recently the College was given a back to back award of excellence for having topnotchers in the board examination and a high passing rate in the board examination for other courses.`
const P23 = `With elections conducted this year, there has been a changing of the guard. Hon. Luis J. Jalandoni III comes back to serve as Mayor and Chairman of the Board. With the able leadership of the honorable Mayor Luis J. Jalandoni III and the administration of Dr. Fatima Bullos, the City College looks forward to having more years of being a "College for the People" and catalyst for positive change, development and progress.`
const P24 = `Together with our chairman and members of the Board, Administrators, Faculty and Staff, we fervently hope that our investment in the education of our youths will pay off the best interest. May this institution aptly called "A College for the People," continue to be a catalyst for change, progress and development. In November 24, 2016, La Carlota City College celebrated its golden year with the theme, "Five Decades Remarkable Leap: Commitment, Service, Excellence." Today it has a total of 165 personnel. 39 of which are non-teaching with 4 contractual and 35 permanent status, 109 compose the teaching personnel with 73 part time and 36 full time status, and 17 are members of the Job order personnel.`

const paragraphs = [ P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19, P20, P21, P22, P23, P24 ];
export default paragraphs;